#pragma once
#define ZPH_MOUSE_BUTTON_1         0
#define ZPH_MOUSE_BUTTON_2         1
#define ZPH_MOUSE_BUTTON_3         2
#define ZPH_MOUSE_BUTTON_4         3
#define ZPH_MOUSE_BUTTON_5         4
#define ZPH_MOUSE_BUTTON_6         5
#define ZPH_MOUSE_BUTTON_7         6
#define ZPH_MOUSE_BUTTON_8         7
#define ZPH_MOUSE_BUTTON_LAST      ZPH_MOUSE_BUTTON_8
#define ZPH_MOUSE_BUTTON_LEFT      ZPH_MOUSE_BUTTON_1
#define ZPH_MOUSE_BUTTON_RIGHT     ZPH_MOUSE_BUTTON_2
#define ZPH_MOUSE_BUTTON_MIDDLE    ZPH_MOUSE_BUTTON_3